# HTTP Server
server:
  port: 18885  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller