version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network

  ts-ui-dashboard:
    build: ts-ui-dashboard
    image: ${IMG_REPO}/ts-ui-dashboard:${IMG_TAG}
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

  ts-auth-service:
    build: ts-auth-service
    image: ${IMG_REPO}/ts-auth-service:${IMG_TAG}
    restart: always
    ports:
      - 12340:12340
    networks:
      - my-network

  ts-auth-mongo:
    image: mongo
    networks:
      - my-network

  ts-user-service:
    build: ts-user-service
    image: ${IMG_REPO}/ts-user-service:${IMG_TAG}
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network

  ts-user-mongo:
    image: mongo
    networks:
      - my-network

  ts-route-service:
    build: ts-route-service
    image: ${IMG_REPO}/ts-route-service:${IMG_TAG}
    restart: always
    ports:
      - 11178:11178
    networks:
      - my-network

  ts-route-mongo:
    image: mongo
    networks:
      - my-network

  ts-train-service:
    build: ts-train-service
    image: ${IMG_REPO}/ts-train-service:${IMG_TAG}
    restart: always
    ports:
      - 14567:14567
    networks:
      - my-network

  ts-train-mongo:
    image: mongo
    networks:
      - my-network

  ts-travel-service:
    build: ts-travel-service
    image: ${IMG_REPO}/ts-travel-service:${IMG_TAG}
    restart: always
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel-mongo:
    image: mongo
    networks:
      - my-network

  ts-station-service:
    build: ts-station-service
    image: ${IMG_REPO}/ts-station-service:${IMG_TAG}
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-station-mongo:
    image: mongo
    networks:
      - my-network

  ts-gateway-service:
    build: ts-gateway-service
    image: ${IMG_REPO}/ts-gateway-service:${IMG_TAG}
    restart: always
    ports:
      - 18888:18888
    networks:
      - my-network

networks:
  my-network:
    driver: bridge